layout_spectrum: 0.9930287
typography_spectrum: 0.5286883
color:
  saturation: 0.1840444
  lightness: 0.882261
  brandStrength: 0.9290879
  rhythmicContrast: 0.2690452
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: JonTheDweeb
