name: JonTheDweeb
favicon: null
layout_spectrum: 0.7485
typography_spectrum: 0.5286883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a83ae'
    - '#7effff'
    - '#2caed2'
    - '#2ddaff'
    - '#e5ffff'
  brandStrength: 1
  lightness: 0.882261
  saturation: 0.1840444
  rhythmicContrast: 0.2690452
purpose: []
